WINDOW_WIDTH = 240
WINDOW_HEIGHT = 160
WINDOW_SIZE = WINDOW_WIDTH, WINDOW_HEIGHT

SCALED_WINDOW_WIDTH = 960
SCALED_WINDOW_HEIGHT = 640
SCALED_WINDOW_SIZE = SCALED_WINDOW_WIDTH, SCALED_WINDOW_HEIGHT

WINDOW_SCALE = SCALED_WINDOW_WIDTH/WINDOW_WIDTH

CAPTION = "Hop, Skip, Jump"
FRAMERATE = 60

LEVEL_SIZE = 160, 147
LEVEL_POSITION = 75, 6